### ISSUE TITLE
issue with --help

### ISSUE THREAD

**Issue by hershwin** [wavefancy/LDpredChrByChr#1]
Hi, thank you so much for the update. When I try to load --help in coord, I get the error: 

> Traceback (most recent call last):
>   File "/ldpred1.0/LDpredChrByChr/LDpred.py", line 4, in <module>
>     from ldpred import coord_genotypes
>   File "/ldpred1.0/LDpredChrByChr/ldpred/coord_genotypes.py", line 207
>     sys.stderr.write(f'non match at: {g_sids[g_i]} - ssid:{ss_sids[ss_i]}, g_nt: {g_nt[0]} - {g_nt[1]}, ss_nt: {ss_nt[0]} - {ss_nt[1]}\n')

The command I am using is 
`python /ldpred1.0/LDpredChrByChr/LDpred.py coord -h`
the original ldpred1.0 does not have this issue. 

Thanks for your help!

**Comment by wavefancy** [comment]
It worked for me:
```
 python3 /medpop/esp2/wallace/tools/LDpred/1.0_wallace/LDpred.py coord -h
usage: LDpred coord [-h] --gf GF --ssf SSF [--N N] --out OUT [--vbim VBIM]
                    [--vgf VGF] [--ilist ILIST] [--skip-coordination] [--beta]
                    [--maf MAF] [--ssf-format {PGC,STANDARD,CUSTOM,GIANT}]
                    [--rs RS] [--A1 A1] [--A2 A2] [--pos POS] [--info INFO]
                    [--chr CHR] [--reffreq REFFREQ] [--pval PVAL] [--eff EFF]
                    [--ncol NCOL]
```
I also checked the git version, it's the same as my local one. 

Can you please provide me more information? 

Best regards
Wallace

**Comment by hershwin** [comment]
It was because I did not download all the necessary packages. The error resolved after I installed docopt. Thanks!
